### PR TITLE
Hackaton quesebifurcan danse

### PR DESCRIPTION
**Pull request by danse**
@quesebifurcan

### CODE REVIEW

**Comment by quesebifurcan** [comment]
Looks good. But could you gitignore app.js as well?

**Comment by danse** [comment]
hum it is ignored

**Comment by danse** [comment]
`public/clj/app.js`

**Comment by gr2m** [comment]
ehm what's the exact problem here?

**Comment by danse** [comment]
no worries ... since we were working in three, we asked Pat and Matt the permission to work on a branch here

**Comment by gr2m** [comment]
this should fix your problems https://github.com/eHealthAfrica/joffrey-example/commit/34292e6920f4c10c533552a7105b6fd6f747fd08

**Pull request merged**
